### ISSUE TITLE
Header checking is case sensitive

### ISSUE THREAD

**Issue by ithinkihaveacat** [RaymiiOrg/ssl-decoder#10]
Header checking (as [here](https://github.com/RaymiiOrg/ssl-decoder/blob/ddb3de9376b310127ee61d20b577c3d0f037b83e/functions/connection.php#L501)) is not done case insensitively. This leads to sites incorrectly being flagged as not supporting strict transport security when in fact they do.

(Maybe use [array_change_key_case](http://php.net/manual/en/function.array-change-key-case.php) on the headers array.)

**Comment by RaymiiOrg** [comment]
Fixed in 4fe949d9b1b04233e5c990988a783e0a8890ab40. 

HTTP headers are not case sensitive (RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", Section 4.2, "Message Headers":  Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive. The updating RFC 7230 does not list any changes from RFC 2616 at this part.
